prSections:
  - title: My Pull Requests
    filters: is:open author:@me
    type: null
  - title: Needs My Review
    filters: is:open review-requested:@me
    type: null
  - title: Involved
    filters: is:open involves:@me -author:@me
    type: null

issuesSections:
  - title: My Issues
    filters: is:open author:@me
  - title: Assigned
    filters: is:open assignee:@me
  - title: Involved
    filters: is:open involves:@me -author:@me

repo:
  branchesRefetchIntervalSeconds: 30
  prsRefetchIntervalSeconds: 60

defaults:
  preview:
    open: true
    width: 50
  prsLimit: 20
  issuesLimit: 20
  view: prs
  layout:
    prs:
      updatedAt:
        width: 5
      repo:
        width: 20
      author:
        width: 15
      assignees:
        width: 20
        hidden: true
      base:
        width: 15
        hidden: true
      lines:
        width: 15
    issues:
      updatedAt:
        width: 5
      repo:
        width: 15
      creator:
        width: 10
      assignees:
        width: 20
        hidden: true
  refetchIntervalMinutes: 30

keybindings:
  universal: []
  issues: []
  prs: []
  branches: []

repoPaths: {}

theme:
  colors:
    background:
      selected: "#282727"
    border:
      faint: "#282727"
      primary: "#282727"
      secondary: "#282727"
    text:
      faint: "#625e5a"
      inverted: "#181616"
      primary: "#dcd7ba"
      secondary: "#c8c093"
      success: "#87a987"
      warning: "#b6927b"
  ui:
    sectionsShowCount: true
    table:
      showSeparator: true
      compact: false

pager:
  diff: ""

confirmQuit: true
