prSections:
  - title: My PRs
    filters: is:open author:@me
  - title: Review Requested
    filters: is:open review-requested:@me
  - title: Involved
    filters: is:open involves:@me -author:@me

issuesSections:
  - title: My Issues
    filters: is:open author:@me
  - title: Assigned
    filters: is:open assignee:@me
  - title: Involved
    filters: is:open involves:@me -author:@me

repo:
  branchesRefetchIntervalSeconds: 30
  prsRefetchIntervalSeconds: 60

defaults:
  preview:
    open: true
    width: 80
  prsLimit: 20
  issuesLimit: 20
  view: prs
  layout:
    prs:
      updatedAt:
        width: 5
      repo:
        width: 20
      author:
        width: 15
      assignees:
        width: 20
        hidden: true
      base:
        width: 15
        hidden: true
      lines:
        width: 15
    issues:
      updatedAt:
        width: 5
      repo:
        width: 15
      creator:
        width: 10
      assignees:
        width: 20
        hidden: true
  refetchIntervalMinutes: 30

keybindings:
  universal: []
  issues: []
  prs:
    - key: C
      name: code review
      command: zellij action new-pane --stacked --close-on-exit -n "PR {{.RepoName}} {{.HeadRefName}} (#{{.PrNumber}})" -- sh -c 'echo "Loading code review for PR {{.RepoName}} {{.HeadRefName}} ({{.PrNumber}})..." && tuicr pr {{.RepoName}}#{{.PrNumber}}'
  branches: []

repoPaths: {
  ourfuturehealth/linked-data-pipeline: ~/projects/work/ld-pipeline,
  ourfuturehealth/linked-data-synthetic-data-generator: ~/projects/work/ld-synthetic,
  ourfuturehealth/linked-data-dictionaries: ~/projects/work/ld-dictionaries,
  ourfuturehealth/linked-data-dml-file-generator: ~/projects/work/ld-dml,
  ourfuturehealth/carrot-mapper: ~/projects/work/ld-carrot-mapper,
}

theme:
  colors:
    background:
      selected: "#282727"
    border:
      faint: "#282727"
      primary: "#282727"
      secondary: "#282727"
    text:
      faint: "#625e5a"
      inverted: "#181616"
      primary: "#dcd7ba"
      secondary: "#c8c093"
      success: "#87a987"
      warning: "#b6927b"
  ui:
    sectionsShowCount: true
    table:
      showSeparator: true
      compact: false

pager:
  diff: ""

confirmQuit: true
smartFilteringAtLaunch: true
