theme = "kanagawa-dragon-improved"

[editor]
bufferline = "always"
color-modes = true
end-of-line-diagnostics = "hint"
idle-timeout = 10
jump-label-alphabet = "jfkdslahgvncmrueiwoty"
line-number = "relative"
rulers = [88]
scrolloff = 10
shell = ["zsh", "-c"]
text-width = 88
true-color = true

[editor.inline-diagnostics]
cursor-line = "error"
# other-lines = "error"

[editor.whitespace.render]
newline = "all"
tab = "all"

[editor.whitespace.characters]
newline = "·"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.auto-save]
after-delay.enable = true
after-delay.timeout = 3000

[editor.indent-guides]
render = true

[editor.file-picker]
hidden = false

[editor.lsp]
auto-signature-help = false
display-messages = true

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name"]
mode.insert = "I"
mode.normal = "N"
mode.select = "S"

[keys.insert]
C-c = "signature_help"

[keys.normal]
"'" = ["goto_word", "goto_definition"]
";" = "goto_word"
"backspace" = "goto_word"
"S-tab" = "shrink_selection"
"tab" = "expand_selection"
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"
A-j = "@15zj"
A-k = "@15zk"
S-d = "kill_to_line_end"
S-h = "goto_previous_buffer"
S-l = "goto_next_buffer"
X = "extend_line_up"
esc = ["collapse_selection", "keep_primary_selection"]
"ret" = "goto_definition"

# Files
[keys.normal.space.space]
w = ":write"
W = ":write!"
a = ":write-all"
A = ":write-all!"
q = ":quit"
Q = ":quit!"

[keys.normal.space.b]
b = "buffer_picker"
c = ":write-buffer-close"
d = ":buffer-close"
h = ":hsplit-new"
n = "goto_next_buffer"
o = ":buffer-close-others"
p = "goto_previous_buffer"
v = ":vsplit-new"
w = ":write-all"

[keys.normal.minus]
"minus" = ["move_prev_sub_word_start", "move_next_sub_word_end"]
"w" = "move_next_sub_word_start"
"b" = "move_prev_sub_word_start"
"e" = "move_next_sub_word_end"

[keys.select.minus]
"minus" = ["extend_prev_sub_word_start", "extend_next_sub_word_end"]
"w" = "extend_next_sub_word_start"
"b" = "extend_prev_sub_word_start"
"e" = "extend_next_sub_word_end"

[keys.select]
"$" = "goto_line_end"
"0" = "goto_line_start"
"_" = "goto_first_nonwhitespace"
"}" = "goto_next_paragraph"
"{" = "goto_prev_paragraph"
