theme = "kanagawa-dragon-improved"

[editor]
bufferline = "always"
color-modes = true
cursorcolumn = true
cursorline = true
idle-timeout = 10
jump-label-alphabet = "fjdkslghabnvmctyrueiwoxqpz"
line-number = "relative"
rulers = [88]
scrolloff = 10
shell = ["zsh", "-c"]
text-width = 88
true-color = true

[editor.whitespace.render]
newline = "all"
tab = "all"

[editor.whitespace.characters]
newline = "·"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.auto-save]
after-delay.enable = true
after-delay.timeout = 3000

[editor.indent-guides]
render = true

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name"]
mode.insert = "I"
mode.normal = "N"
mode.select = "S"

[keys.normal]
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"
S-d = "kill_to_line_end"
esc = ["collapse_selection", "keep_primary_selection"]

[keys.normal.space.b]
b = "buffer_picker"
c = ":write-buffer-close"
d = ":buffer-close"
h = ":hsplit-new"
n = "goto_next_buffer"
o = ":buffer-close-others"
p = "goto_previous_buffer"
v = ":vsplit-new"
w = ":write-all"

[keys.select]
"}" = "goto_next_paragraph"
"{" = "goto_prev_paragraph"
