# Python
[[language]]
name = "python"
scope = "source.python"
injection-regex = "python"
comment-token = "#"
language-servers = [
  { name = "pyright", except-features = [ "format" ] },
  { name = "ruff", except-features = [ "diagnostics" ] },
  { name = "typos" },
]
indent = { tab-width = 4, unit = "    " }
# formatter = { command = "ruff", args = ["format", "--stdin-filename", "{}"] }
auto-format = true

# Markdown
[[language]]
name = "markdown"
formatter = { command = "dprint", args = ["fmt", "--stdin", "md", "--config", "~/.config/dprint/config.json"] }
language-servers = [ "marksman", "typos"]
text-width = 88
indent = { tab-width = 4, unit = "    " }
auto-format = true

# Pyright Language Server
[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]
[language-server.pyright.config]
venvPath = "."
venv = ".venv"
pythonPath = ".venv/bin/python"
[language-server.pyright.config.python.analysis]
typeCheckingMode = "standard"
autoImportCompletions = true
extraPaths = [ "src" ]

# Ruff
[language-server.ruff]
command = "/opt/homebrew/bin/ruff"
args = ["server"]

# Spell checker
[language-server.typos]
command = "typos-lsp"
environment = {"RUST_LOG" = "error"}
config.diagnosticSeverity = "Warning"
