# --- PYTHON --------------------------------------------------------------------------

[[language]]
name = "python"
scope = "source.python"
injection-regex = "python"
comment-token = "#"
language-servers = [
  { name = "pyright", except-features = [ "format" ] },
  { name = "ruff" },
  { name = "typos" },
]
indent = { tab-width = 4, unit = "    " }
formatter = { command = "bash", args = ["-c", "ruff check --select I --fix - | ruff format -"]}
# formatter = { command = "ruff", args = ["format", "--stdin-filename", "{}"] }
auto-format = true

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.pyright.config]
venvPath = "."
venv = ".venv"
pythonPath = ".venv/bin/python"

[language-server.pyright.config.python.analysis]
typeCheckingMode = "standard"
autoImportCompletions = true
extraPaths = [ "src" ]

[language-server.ruff]
command = "/opt/homebrew/bin/ruff"
args = ["server"]

# --- MARKDOWN ------------------------------------------------------------------------

[[language]]
name = "markdown"
formatter = { command = "dprint", args = ["fmt", "--stdin", "md"] }
language-servers = [ "marksman", "typos"]
text-width = 80
rulers = [80]
indent = { tab-width = 4, unit = "    " }
auto-format = true

# --- YAML ----------------------------------------------------------------------------

[[language]]
name = "yaml"
formatter = { command = "dprint", args = ["fmt", "--stdin", "yaml" ]}
file-types = ["yaml", "yml"]
text-width = 80
rulers = [80]
auto-format = true

# --- GENERIC ------------------------------------------------------------------------

# Spell checker
[language-server.typos]
command = "typos-lsp"
environment = {"RUST_LOG" = "error"}
config.diagnosticSeverity = "Warning"
