inherits = "kanagawa-dragon"

"ui.background" = { fg = "dragonBlack6", bg = "dragonBlack0"}
"ui.bufferline.active" = { fg = "dragonGray2", bg = "dragonBlack0" }
"ui.bufferline.background" = { bg = "dragonBlack0" }
"ui.bufferline" = { fg = "dragonBlack6", bg = "dragonBlack0" }
"ui.cursorcolumn.primary" = { bg = "dragonBlack4" }
"ui.cursorline.primary" = { bg = "dragonBlack4" }
"ui.gutter" = { fg = "dragonBlack0", bg = "dragonBlack0" }
"ui.help" = { fg = "fujiWhite", bg = "dragonBlack0" }
"ui.linenr.selected" = { fg = "dragonGray2", modifiers = ["bold"] }
"ui.linenr" = { fg = "dragonBlack5", bg = "dragonBlack0" }
"ui.menu.scroll" = { fg = "oldWhite", bg = "dragonBlack4" }
"ui.menu.selected" = { fg = "fujiWhite", bg = "dragonBlack6", modifiers = ["bold"] }
"ui.menu" = { fg = "dragonGray", bg = "dragonBlack0" }
"ui.popup" = { fg = "oldWhite", bg = "dragonBlack0" }
"ui.statusline.inactive" = { fg = "fujiGray", bg = "dragonBlack0" }
"ui.statusline" = { fg = "oldWhite", bg = "dragonBlack0" }
"ui.text.focus" = { fg = "fujiWhite", bg = "dragonBlack4", modifiers = ["bold"] }
"ui.text" = "fujiWhite"
"ui.virtual.jump-label" = { fg = "autumnRed" }
"ui.virtual.ruler" = { bg = "dragonBlack3" }
"ui.window" = { fg = "dragonBlack3" }

[palette]
dragonBlack0 = "#000000"
dragonBlack1 = "#12120f"
dragonBlack2 = "#1D1C19"
dragonBlack3 = "#181616"
dragonBlack4 = "#282727"
dragonBlack5 = "#393836"
dragonBlack6 = "#625e5a"

dragonWhite = "#c5c9c5"
dragonGreen = "#87a987"
dragonGreen2 = "#8a9a7b"
dragonPink = "#a292a3"
dragonOrange = "#b6927b"
dragonOrange2 = "#b98d7b"
dragonGray = "#a6a69c"
dragonGray2 = "#9e9b93"
dragonGray3 = "#7a8382"
dragonBlue2 = "#8ba4b0"
dragonViolet= "#8992a7"
dragonRed = "#c4746e"
dragonAqua = "#8ea4a2"
dragonAsh = "#737c73"
dragonTeal = "#949fb5"
dragonYellow = "#c4b28a"

