# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$directory\
$character\
"""

right_format = """
$cmd_duration\
$direnv\
$git_branch\
${custom.git_status_dirty}\
$git_status\
$battery\
"""

continuation_prompt = "[> ](white)"

palette = "kanagawa_dragon"

[username]
style_user = "dragon_black6"
format = "[$user]($style)"
disabled = false
show_always = false

[directory]
truncate_to_repo = true
truncation_length = 4
style = "yellow"
format = "[$path]($style)"
home_symbol = "~"

[character]
success_symbol = " [→](white)"
error_symbol = " [→](red)"
# vicmd_symbol = " [→](purple)"

[git_branch]
format = "[$branch]($style)"
style = "white"

[custom.git_status_dirty]
when = 'test -n "$(git status --porcelain 2>/dev/null)"'
symbol = "dirty"
format="[\\(](white)[$symbol](red)[\\)](white)"
shell = ["sh"]

[git_status]
format = '( [\[$ahead_behind$stashed\]]($style))'
style = "white"
stashed = "≡"
ahead = "↑${count}"
behind = "↓${count}"

[cmd_duration]
format = "[\\($duration\\) ]($style)"
style = "dragon_black6"

[direnv]
disabled = false
format = "[$allowed]($style) "
style = "dragon_black6"
allowed_msg = "•"
not_allowed_msg = "direnv not allowed"

[battery]
format = "[$symbol](spring_green)[ ]($style)[${percentage}](bold fg:dragon_black3 bg:$style)[]($style)"
charging_symbol = ""
discharging_symbol = ""
full_symbol = ""
unknown_symbol = ""
empty_symbol = ""


[[battery.display]]
threshold = 10
style = "autumn_red"

[[battery.display]]
threshold = 20
style = "autumn_yellow"

[palettes.kanagawa_dragon]
sumi_ink0 = "#16161D"
sumi_ink1 = "#181820"
sumi_ink2 = "#1a1a22"
sumi_ink3 = "#1F1F28"
sumi_ink4 = "#2A2A37"
sumi_ink5 = "#363646"
sumi_ink6 = "#54546D"
wave_blue1 = "#223249"
wave_blue2 = "#2D4F67"
winter_green = "#2B3328"
winter_yellow = "#49443C"
winter_red = "#43242B"
winter_blue = "#252535"
autumn_green = "#76946A"
autumn_red = "#C34043"
autumn_yellow = "#DCA561"
samurai_red = "#E82424"
ronin_yellow = "#FF9E3B"
dragon_blue = "#658594"
old_white = "#C8C093"
fuji_white = "#DCD7BA"
fuji_gray = "#727169"
oni_violet = "#957FB8"
oni_violet2 = "#b8b4d0"
crystal_blue = "#7E9CD8"
spring_violet1 = "#938AA9"
spring_violet2 = "#9CABCA"
spring_blue = "#7FB4CA"
light_blue = "#A3D4D5"
wave_aqua1 = "#6A9589"
wave_aqua2 = "#7AA89F"
wave_aqua3  = "#68AD99"
wave_aqua4  = "#7AA880"
wave_aqua5  = "#6CAF95"
spring_green = "#98BB6C"
boat_yellow1 = "#938056"
boat_yellow2 = "#C0A36E"
carp_yellow = "#E6C384"
sakura_pink = "#D27E99"
wave_red = "#E46876"
peach_red = "#FF5D62"
surimi_orange = "#FFA066"
katana_gray = "#717C7C"
dragon_black0 = "#0d0c0c"
dragon_black1 = "#12120f"
dragon_black2 = "#1D1C19"
dragon_black3 = "#181616"
dragon_black4 = "#282727"
dragon_black5 = "#393836"
dragon_black6 = "#625e5a"
dragon_white = "#c5c9c5"
dragon_green = "#87a987"
dragon_green2 = "#8a9a7b"
dragon_pink = "#a292a3"
dragon_orange = "#b6927b"
dragon_orange2 = "#b98d7b"
dragon_gray = "#a6a69c"
dragon_gray2 = "#9e9b93"
dragon_gray3 = "#7a8382"
dragon_blue2 = "#8ba4b0"
dragon_viole = "#8992a7"
dragon_red = "#c4746e"
dragon_aqua = "#8ea4a2"
dragon_ash = "#737c73"
dragon_teal = "#949fb5"
dragon_yellow = "#c4b28a"
