[notebook]
dir = "~/notebook"

[note]
language = "en"
default-title = "Untitled"
filename = "{{id}}-{{slug title}}"
id-charset = "alphanum"
id-length = 5
id-case = "lower"
extension = "md"
template = "default.md"

[extra]
author = "Luke Marques"

[group.daily]
paths = ["journal/daily"]

[group.daily.note]
filename = "{{format-date now}}"
extension = "md"
template = "daily.md"

[format.markdown]
hashtags = true  # support `#hastags`
colon-tags = true  # support `:colon:separated:tags:`

[tool]
editor = "hx"
shell = "/bin/zsh"
pager = "bat -p"
fzf-preview = "bat -p --color always {-1}"

[filter]
recents = "--sort created- --created-after 'last two weeks'"

[alias]
edlast = "zk edit --limit 1 --sort modified- $@"
recent = "zk edit --sort created- --created-after 'last two weeks' --interactive"
lucky = "zk list --quiet --format full --sort random --limit 1"
daily = 'zk new --no-input "$ZK_NOTEBOOK_DIR/journal/daily"'

[lsp]

[lsp.diagnostics]
wiki-title = "hint"
dead-link = "error"
