[theme]
dark = "kanagawa-dragon-improved"
light = "wolf-alabaster-light-bg"

[editor]
bufferline = "never"
color-modes = true
end-of-line-diagnostics = "hint"
idle-timeout = 10
jump-label-alphabet = "jfkdslahgvncmrueiwoty"
line-number = "relative"
rulers = [88]
scrolloff = 10
shell = ["zsh", "-c"]
text-width = 88
true-color = true

[editor.inline-diagnostics]
cursor-line = "hint"
# other-lines = "error"

[editor.whitespace.render]
newline = "all"
tab = "all"

[editor.whitespace.characters]
newline = "·"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.auto-save]
after-delay.enable = true
after-delay.timeout = 3000

[editor.indent-guides]
render = true

[editor.file-picker]
hidden = false

[editor.lsp]
# auto-signature-help = false
display-messages = true

[editor.statusline]
left = ["mode", "spinner", "version-control", "spacer", "file-name", "spacer", "read-only-indicator", "file-modification-indicator"]
mode.insert = "I"
mode.normal = "N"
mode.select = "S"

[keys.insert]
C-c = "signature_help"

[keys.normal]
"'" = "goto_word"
";" = "goto_word"
"backspace" = "goto_word"
"S-tab" = "shrink_selection"
"tab" = "expand_selection"
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"
A-j = "@10zj"
A-k = "@10zk"
S-d = "kill_to_line_end"
S-h = "goto_previous_buffer"
S-l = "goto_next_buffer"
X = "extend_line_up"
esc = ["collapse_selection", "keep_primary_selection"]
"ret" = "goto_definition"

[keys.normal.space]
l = "buffer_picker"
e = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file',
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
  ':set mouse false',
  ':set mouse true',
]
o = ':sh zellij run -c -f --name="Search and Replace" -- scooter'
t = [
  ":set mouse false",
  ":insert-output lazygit",
  ":redraw",
  ":set mouse true",
  ":open /tmp/lazygit_out.txt",
  # "select_all",
  # "split_selection_on_newline",
  # "goto_file",
  ":buffer-close! /tmp/lazygit_out.txt",
  ":sh rm -f /tmp/lazygit_out.txt",
  ":rla",
  # ":buffer-close",
]

# Word counts
[keys.normal.space.W]
w = ":sh echo \"%{selection}\" | wc -w"  # Word count
c = ":sh echo \"%{selection}\" | wc -m"  # Character count
l = ":sh echo \"%{selection}\" | wc -l"  # Line count

# Git/github operations
[keys.normal.space.g]
f = "changed_file_picker"
# Git blame
b = ":sh git -C $(dirname $(realpath %{buffer_name})) blame -L %{cursor_line},%{cursor_line} $(realpath %{buffer_name})"
# Lazygit
l = [
  ":set mouse false",
  ":insert-output lazygit",
  ":redraw",
  ":set mouse true",
  ":open /tmp/lazygit_out.txt",
  # "select_all",
  # "split_selection_on_newline",
  # "goto_file",
  ":buffer-close! /tmp/lazygit_out.txt",
  ":sh rm -f /tmp/lazygit_out.txt",
  ":rla",
  # ":buffer-close",
]


# Files
[keys.normal.space.space]
w = ":write"
W = ":write!"
a = ":write-all"
A = ":write-all!"
q = ":quit"
Q = ":quit!"
r = ":reload-all"

[keys.normal.space.b]
b = "buffer_picker"
# B = "pinned_buffer_picker"
# p = ":buffer-pin"
# u = ":buffer-unpin"
c = ":write-buffer-close"
C = ":write-buffer-close!"
d = ":buffer-close"
D = ":buffer-close!"
# o = ":buffer-close-others-unpinned"
# O = ":buffer-close-others-unpinned!"
# a = ":buffer-close-all-unpinned"
# A = ":buffer-close-all-unpinned!"

[keys.normal.minus]
"minus" = ["move_prev_sub_word_start", "move_next_sub_word_end"]
"w" = "move_next_sub_word_start"
"b" = "move_prev_sub_word_start"
"e" = "move_next_sub_word_end"

[keys.select.minus]
"minus" = ["extend_prev_sub_word_start", "extend_next_sub_word_end"]
"w" = "extend_next_sub_word_start"
"b" = "extend_prev_sub_word_start"
"e" = "extend_next_sub_word_end"

[keys.select]
"$" = "goto_line_end"
"0" = "goto_line_start"
"_" = "goto_first_nonwhitespace"
"}" = "goto_next_paragraph"
"{" = "goto_prev_paragraph"
"'" = "goto_word"
";" = "goto_word"
"backspace" = "goto_word"
